### PR TITLE
Identities fixes

### PR DESCRIPTION
**Pull request by kvviecien**
* Add links to alias management (https://runbox.com/mail/account_alias)
-- On Identities page - [Screenshot](https://i.imgur.com/u0OzFz7.png)
-- In the edit dialog (only if editing an alias) - [Screenshot](https://i.imgur.com/AHnlVBL.png)
* Remove Delete button from aliases and current default identity (the one visible on the top)
* Remove alias count info
* Add warning for the user if they reached maximum number of allowed aliases - [Screenshot](https://i.imgur.com/U31jaLw.png)

### CODE REVIEW

**Comment by gtandersen** [comment]
Looks good @kvviecien!

Can we change the text "To manage your aliases visit this page." to "To manage your aliases, visit Account > Aliases."? 

This would be more specific and would help users navigate our pages. :)

**Comment by gtandersen** [comment]
We may also need an error message such as "You have reached the maximum allowed number of Runbox aliases." if a user tries to create more than 100 aliases with domainid == 0.

**Comment by kvviecien** [comment]
> Looks good @kvviecien!
> 
> Can we change the text "To manage your aliases visit this page." to "To manage your aliases, visit Account > Aliases."?
> 
> This would be more specific and would help users navigate our pages. :)

Wouldn't that confuse a user since this navigation is not a part of Runbox7? I don't think users go to Runbox6 to look for stuff. Maybe "To manage your aliases, visit [Alias Administration](https://runbox.com/mail/account_alias)." since that's the name of that page? 




> We may also need an error message such as "You have reached the maximum allowed number of Runbox aliases." if a user tries to create more than 100 aliases with domainid == 0.

You're right, I'll set to display this if a user already has 100 aliases.

**Comment by gtandersen** [comment]
> > Can we change the text "To manage your aliases visit this page." to "To manage your aliases, visit Account > Aliases."?
> > This would be more specific and would help users navigate our pages. :)
> 
> Wouldn't that confuse a user since this navigation is not a part of Runbox7? I don't think users go to Runbox6 to look for stuff. Maybe "To manage your aliases, visit [Alias Administration](https://runbox.com/mail/account_alias)." since that's the name of that page?

Agreed -- the point was mainly that we should avoid links that say "this link" or "this page". :)

**Comment by kvviecien** [comment]
Added discussed changes, updated screenshots in the [first comment](https://github.com/runbox/runbox7/pull/961#issue-616188239).

**Review by gtandersen — APPROVED** [review]
Very nice @kvviecien!

**Pull request merged**
