### PR TITLE
Sync index on foldercount mismatch

### PR DESCRIPTION
**Pull request by petersalomonsen**
This PR adds comparing folder counts received from the server (which is displayed in the left side menu), with the actual count per folder in the local search index. If there are discrepancies, the current folder in view will be retrieved from the server, and added to the index. If the next compare still show discrepancies, a dialog will pop up and suggest downloading a fresh index from the server.

A cause of discrepancies is that the folder count from the server includes messages marked for deletion ( as mentioned in https://github.com/runbox/runbox7/issues/190 ). To prevent this we should decide on either supporting strikethrough of messages marked from deletion in Runbox7, or remove them from the counters as suggested in the issue.

### CODE REVIEW

**Comment by gtandersen** [comment]
@petersalomonsen The first change which compares folder counts only have benefits AFAICT.

Regarding strike-throughs then supporting this in user interfaces seems to be uncommon, so removing them from the folder counts appears to be the best solution.

**Comment by petersalomonsen** [comment]
ok, for the folder count to exclude messages marked for deletion, that would have to be on the server.

Also another issue I found after testing this was that while it does download all message headers for a folder on discrepancies, and add them to the indexer again, it does not remove those that are deleted or moved to another folder - so you could end up with too many messages in the local index for that folder. I'll try to come up with something there ( so still not ready for merge ).

also have to fix the commit messages.

**Comment by petersalomonsen** [comment]
The latest commit ( https://github.com/runbox/runbox7/pull/231/commits/4ff6c19 ) adds a check for messages that are in the local index but not on the server, and sends a verification requests for these messages which will either update the changed_date or deleted timestamp, which then again will be picked up on next check for messages to be synced from the server.

What still remains is to handle messages marked for deletion (deleted flag), and since we're not going to show these (with strikethrough), a solution might be that the Runbox7 app actually deletes these messages from the server. Will that be a problem ? ( @davidbowdley you might have an opinion on this ).

**Comment by petersalomonsen** [comment]
Latest commit shows messages marked for deletion with a unicode recycle symbol (didn't find trash), also a tooltip explaining why.

Runbox7markdelete

**Comment by petersalomonsen** [comment]
Also added a missing DKIMModule import ( https://github.com/runbox/runbox7/pull/231/files#diff-fc6b22833aeaf77f8440c4970ade705eR136 )  that caused the tests to fail from this commit https://github.com/runbox/runbox7/commit/babd3dcf1549276cc9eb1612e10be320b49aaefb @hernan604

**Comment by gtandersen** [comment]
Looks good @petersalomonsen !

**Pull request merged**
