### PR TITLE
Subscriptions & Payments (settings hub)

### PR DESCRIPTION
**Pull request by kvviecien**
Applied [changes suggested by Geir](https://github.com/runbox/runbox7/pull/927#issuecomment-814675136).

Addons and Main Account Plans got merged together into **Plans & Upgrades**. 
Addons component now lives inside the Upgrades component

Path /account/addons redirects to /account/upgrades.

### CODE REVIEW

**Review by gtandersen — APPROVED** [review]
Great, @kvviecien!

**Review by tadzik — APPROVED** [review]

**Comment by tadzik** [comment]
Looks great – could you fix up the merge conflicts?

**Comment by kvviecien** [comment]
> Looks great – could you fix up the merge conflicts?

Yup! I was waiting for the conflicts! Geir and I were working on the same files so I was waiting for him to merge his PR :)

**Comment by gtandersen** [comment]
Minor issue -- I think we agreed on [these URLs](https://github.com/runbox/runbox7/pull/927#issuecomment-814675136):

- Your Subscriptions: /account/subscriptions
- Plans & Upgrades: /account/plans

**Comment by kvviecien** [comment]
> Minor issue -- I think we agreed on [these URLs](https://github.com/runbox/runbox7/pull/927#issuecomment-814675136):
> 
> * Your Subscriptions: /account/subscriptions
> * Plans & Upgrades: /account/plans
> 
> This would then correspond with [4b22a93](https://github.com/runbox/runbox7/commit/4b22a936dc9cf57d06aab72fd63d0ed7cae2a813).

Oh my, so sorry. I didn't read it carefully so I didn't understand there have to be URL changes too. I'm on it! Will make another PR for it.

**Comment by gtandersen** [comment]
No worries @kvviecien. :)

**Pull request merged**
