### PR TITLE
refactor(mailviewer): Display a list of attachments at the top

### PR DESCRIPTION
**Pull request by castaway**
Add an expandable list of attachments near the top of the email view. Needs some tweaking (please @kvviecien - how do we get the horizontal divider?)

Fixes: #883

### CODE REVIEW

**Comment by castaway** [comment]
image

Hmm need some more icons..

**Comment by gtandersen** [comment]
Nice work @castaway! 

How about one of these for graphics:

https://materialdesignicons.com/icon/file-image
https://materialdesignicons.com/icon/file-image-outline

**Comment by castaway** [comment]
The missing icons on mine are due to backend issues, the attachments extractor uses nodejs mailparser, which doesnt seem to be running on rmm604 ... I should probably switch to 704 ..

**Comment by kvviecien** [comment]
@castaway you can create a divider by using `<mat-divider></mat-divider>` from Angular Material. Is that what you need?

**Comment by gtandersen** [comment]
Looking forward to seeing this in action @castaway. :)

**Comment by castaway** [comment]
With divider:
Closed: 
image

Open:
image

Having both looks a little silly to me in a rather short email.. I assume less so in a long one .. 

Current thoughts: 

* I have it set to "default open, unless mobile" - I think I prefer default closed, regardless..
* Should we make the bottom-of-page list closeable too, or is that just my terrible aesthetic sense?

Parser working now - still missing some file types / a default? need to poke mailparser separately

**Comment by gtandersen** [comment]
Nicely done @castaway!

We could perhaps list the attachments on one line at the top of the message (with or without the small previews), and then the larger versions could ideally be shown near the bottom of the visible window.

Would it be possible to show somewhat larger icons in the bottom preview row? :)

**Pull request closed without merging**
