### PR TITLE
fix(compose): Correct default "From" email for replies

### PR DESCRIPTION
**Pull request by kvviecien**
The Reply option wasn't picking the correct "From" address if the "To"
email was capitalized by the original sender.
The function comparing addresses to find the correct one to reply with
now formats the address, so the casing doesn't break anything.

Fixes: #568

### CODE REVIEW

**Comment by tadzik** [comment]
Will it still work if the To puts the address in angle brackets, like `Test mail person <testmail@testmail.com>`? I'm not sure if `fromObj.email` contains only the actual address or if it includes the name component too.

**Comment by kvviecien** [comment]
fromObj has separate properties for name and email, so fromObj.email has just the address in it.
Turns out the alias names actually don't matter, they can be completely different from the email address.

**Comment by tadzik** [comment]
Hm, you're right – I checked again and now it indeed works as advertised. I must've checked the wrong branch (or browser tab...) the first time around ;) Good job!

A test may be a good idea nonetheless – even if it's not actually an edge case after all.

**Comment by kvviecien** [comment]
Sorry for the mess up with changes above. I forgot I'm working on a fork and I didn't update my copy of the repository with recent changes...

**Pull request merged**
