### PR TITLE
feat(HomePage): Add keyboard shortcuts

### PR DESCRIPTION
**Pull request by MimaIsAwesome**
j go “down” the list
k go “up” the list
gi go to inbox
gt go to sent messages

### CODE REVIEW

**Comment by hernan604** [comment]
Hi  MimaIsAwesome,

travis is complaining because of your last commit message is in the wrong format.

See https://github.com/runbox/runbox7/wiki/Tips-%26-Tricks#travis-ci-complains-the-commit-messages-are-in-the-wrong-format

**Comment by tadzik** [comment]
Hey, thanks for the PR!

The code looks good and works well – good job! There is still a few things we need addressed before we merge it though.

First, like Hernan said, the commit message has the wrong format. It's a bit of a peculiar requirement of ours, but it matches Angular's commit policy and it helps us review the list of things that we later include in our releases. You can check if your commits are alright running `npm run policy` in your console.

Once the commit is done, it's a bit tricky to fix it, but not impossible – if it's just a single commit, a `git commit --amend` will allow you to rewrite the commit message leaving everything else intact. For multiple commits like you have, you can rewrite them with `git rebase --interactive master`. It will open the editor and allow you to decide which commits you want to keep, drop or rename. In your case, you may want to change it to something like this:

```
reword 2782192 ...
fixup 2782192 ...
```

This will keep only one commit of the two you made (since the second is just a fixup), and will open the same editor you know from committing things to allow you to write the commit message anew. After that's done, you can run the policy tests again to see if all is good now. I know this process is a bit awkward, but understanding `git rebase` is a skill worth having :)

The second thing we need to look at is the failing unit tests. You have added a new depedency to FolderListComponent (the HotkeysService), and now its unit tests are failing because they failed to provide the HotkeysService to the tested component. You can see that by running `npm run ci-tests unit`. Your code didn't break any tests, but since the code is now bigger (and better), the tests need to be updated as well.

To fix that, go to `src/app/folder/folderlist.component.spec.ts`. Wherever `new FolderListComponent` is called, you need to pass the HotkeysService as the required 4th argument. Fortunately, the tests don't actually require for any hotkey service to exist, so we can cheat a little, and give it a fake (mocked) HotkeysService instead of a real one. The required changes look somewhat like this:

```
diff --git a/src/app/folder/folderlist.component.spec.ts b/src/app/folder/folderlist.component.spec.ts
index 5ad12a7..051e235 100644
--- a/src/app/folder/folderlist.component.spec.ts
+++ b/src/app/folder/folderlist.component.spec.ts
@@ -29,10 +29,13 @@ import { MatDialogModule } from '@angular/material/dialog';
 import { MatSnackBarModule } from '@angular/material/snack-bar';
 import { NoopAnimationsModule } from '@angular/platform-browser/animations';
 import { DialogModule } from '../dialog/dialog.module';
+import { HotkeysService } from 'angular2-hotkeys';
+
 describe('FolderListComponent', () => {
     let injector: TestBed;
     let service: RunboxWebmailAPI;
     let httpMock: HttpTestingController;
+    let hotkeyMock: HotkeysService;
 
     beforeEach(() => {
         TestBed.configureTestingModule({
@@ -48,6 +51,7 @@ describe('FolderListComponent', () => {
         injector = getTestBed();
         service = injector.get(RunboxWebmailAPI);
         httpMock = injector.get(HttpTestingController);
+        hotkeyMock = { add: _ => null } as HotkeysService;
     });
     it('should empty trash', async(async () => {
         let selectedFolderName: string;
@@ -83,7 +87,8 @@ describe('FolderListComponent', () => {
                 }
             } as MessageListService,
             service,
-            null
+            null,
+            hotkeyMock,
         );
 
         await comp.emptyTrash();
@@ -126,7 +131,7 @@ describe('FolderListComponent', () => {
                 ordered_ids_request = ordered_ids;
                 return of(true);
             }
-        } as RunboxWebmailAPI, null);
+        } as RunboxWebmailAPI, null, hotkeyMock);
 
         console.log('move folder with id 6 above 5');
         await comp.folderReorderingDrop(6, 5, DropPosition.ABOVE);
```

`hotkeyMock` here is our fake HotkeysService that is required for FolderListComponent to work: even though it doesn't do anything :) With these changes in place, our unit tests finally pass.

The last failing bit is the `npm run build`. The production build is always built using dependencies specified in package-lock.json – not just those in package.json. It will bail out if package-lock.json doesn't contain the required dependencies. I know it looks like a local, temporary file, but package-lock.json is actually vital and needs to be commited. You can easily fix that up: `npm install && git commit package-lock.json -m 'build(dependencies): update package-lock.json` should do the trick.

I know it looks like a lot of work still, but the hard part is done – now we just need to make the release process done as well :) I hope my hints were helpful – if it sounds like too much (or too boring :P), let us know and we'll integrate your changes ourselves. But if you want to wrestle with our CI a bit yourself, go ahead :)

**Comment by MimaIsAwesome** [comment]
Thanks a lot for your help and detailed description, i really appreciate it! :)  Of course, i would like to learn the drill about git policy and other stuffs so i would like to do it my self. Thank you again!

**Comment by gtandersen** [comment]
Nice work @MimaIsAwesome and thanks for the contribution!

Let us know where you'd like us to send your [bounty](https://blog.runbox.com/2019/02/runbox-7-feature-and-bug-bounty-program/). :)

-- Geir

**Pull request merged**
