### PR TITLE
feat(menu): Add Contacts and Calendar to sidenav menu for mobile view…

### PR DESCRIPTION
**Pull request by gtandersen**
… and small screens.

### CODE REVIEW

**Comment by tadzik** [comment]
I think this is covered by https://github.com/runbox/runbox7/pull/344/commits/2e3be517b2e14b0d75494f58a71f8ec1b00d8a49.

I stole some of your fixes from here into 43e56659e3e7a33782199552ab31c02532df642b, giving us a layout that looks somewhat like this:
5AvurHS6yp

**Comment by gtandersen** [comment]
Looks great @tadzik, especially if we add Contacts! :)

**Comment by hernan604** [comment]
So this should be deleted ?

**Comment by gtandersen** [comment]
Yes!

**Pull request closed without merging**
