### PR TITLE
Make Identities page mobile and desktop friendly

### PR DESCRIPTION
**Pull request by kvviecien**
Fixes: #819 

<kbd></kbd>

<kbd></kbd>

### CODE REVIEW

**Comment by kvviecien** [comment]
The only problem is that in order to test the mobile/desktop breakpoint (480px) a reload is needed.
It's because there is no other way (that I know of) to manage the Material Grid fully in CSS. A small JS check was needed for that and it sets up values for HTML while it's being loaded.

**Comment by gtandersen** [comment]
Looks great @kvviecien!

**Comment by kvviecien** [comment]
**Editor modal changes**

Mobile:
<kbd></kbd>

Desktop:
<kbd></kbd>

Warning message:
<kbd></kbd>

**Review by gtandersen — APPROVED** [review]
Beautiful!

**Pull request merged**
