### PR TITLE
Fast and correct folder counters

### PR DESCRIPTION
**Pull request by tadzik**
Implements changes described/planned in https://github.com/runbox/runbox7/issues/512.

Suggestions (esp for high-level design) are much welcome.

### CODE REVIEW

**Comment by petersalomonsen** [comment]
Yes I think it's the right approach to calculate the folder counts from the local index. I think I even wanted to do this when I worked on this, so very good that you are picking this up :-) It's for sure confusing when the index and the message db is not in sync, and much better if the index can be the master. Server index and local index should probably be more in sync if I remember correct.

**Comment by gtandersen** [comment]
Agree that the folder counts should be built from the index/list currently in use for consistency in the UI -- if it's a local index then use that, while if it's the database then that should be used.

**Comment by tadzik** [comment]
The folder count updates are now instant and consistent with the local index (if it exists). Calculation seems to take around 5ms per folder on desktop firefox – while the queries themselves are quite inefficient, it seems like they're performant enough in practice to not worry about it too much for now :)

**Comment by tadzik** [comment]
This fixes GH-512

**Pull request merged**
