### PR TITLE
feat(mailviewer): Add select-all option for selecting messages

### LINKED ISSUE #61: Check all (invisible) messages
Currently the "check all" checkbox selects all visible messages. This could be expanded to allow selection of all (invisible) messages in the list via a drop down (shown when clicking and holding the checkbox) with the following options:

* Check none
* Check visible
* Check all

Ref: https://community.runbox.com/t/spam-check-all-messages-doesnt/425

### PR DESCRIPTION
**Pull request by castaway**
Fixes #61

### CODE REVIEW

**Comment by tadzik** [comment]
Few things:

* Deselecting rows seems to only work in "visible" mode. In "all" mode selecting works (although slightly delayed), and clicking again does nothing.

* Selecting all rows in "all", then switching to "visible" mode and deselecting rows leaves the invisible rows selected. This is logical, but it does feel a bit confusing.

* The menu pops up in a weird place, probably due to it being attached (and positioned relatively to) a hidden button. Maybe attaching it the canvastable would make the placement better?

**Comment by castaway** [comment]
> Few things:
> 
> * Deselecting rows seems to only work in "visible" mode. In "all" mode selecting works (although slightly delayed), and clicking again does nothing.
> * Selecting all rows in "all", then switching to "visible" mode and deselecting rows leaves the invisible rows selected. This is logical, but it does feel a bit confusing.
> * The menu pops up in a weird place, probably due to it being attached (and positioned relatively to) a hidden button. Maybe attaching it the canvastable would make the placement better?

Improved/fixed two of those.. 2nd one is a matter of what makes more sense to the user.

**Comment by tadzik** [comment]
Now it seems like the short click is unnecessarily triggering the menu too :P 

Also, it looks a bit cramped:

settings

Maybe splitting it into two lines with some margins would help?

**Comment by gtandersen** [comment]
Looks like a good solution and I agree with the proposed style changes.

**Comment by tadzik** [comment]
Seems to work perfectly now :) I wonder if we want to keep this as a setting in localstorage?

**Review by tadzik — APPROVED** [review]

**Comment by tadzik** [comment]
(Also, travis looks unhappy :()

**Comment by kvviecien** [comment]
> (Also, travis looks unhappy :()

Now it actually can't find the action buttons, so I will add the timeout you suggested as well. Should've listened to you!

**Comment by tadzik** [comment]
> > (Also, travis looks unhappy :()
> 
> Now it actually can't find the action buttons, so I will add the timeout you suggested as well. Should've listened to you!

Well, it's also unhappy about the linter :) But yeah, the fix to e2e flaps will have to be revisited as well :/

**Comment by tadzik** [comment]
There's some unit tests failing due to compilation errors: https://travis-ci.com/github/runbox/runbox7/jobs/399360316#L261

**Comment by castaway** [comment]
> There's some unit tests failing due to compilation errors: https://travis-ci.com/github/runbox/runbox7/jobs/399360316#L261

oops, it was the merge that failed (but not in a way there were conflicts) - now fixed!

**Comment by tadzik** [comment]
All tests pass locally for me, so it must be just Travis complaining about Travis things. Merging.

**Pull request merged**
