### PR TITLE
feat(account): Add a way to access account settings on mobile

### PR DESCRIPTION
**Pull request by tadzik**
This introduces a way to access the account screen from the mobile sidemenu.

Looks like this:

test

Imitating (visually and in behaviour) the same sidemenu as in webmail, contacts etc. This will enable access to all the account-related components and allow the user to switch between them. Before this is rolled out we need to ensure all of these components are actually accesible on mobile, and fix the ones that are not either in this PR or some others.

We can also take the opportunity to rename some of the sections to make them more understandable – something that @davidbowdley has often brought up.

Known issues:

- [x] The main "Account settings" page – we could have it be a hub between all the account-related pages – kind of what /account/components currently is, but not only for products but also for account security, identities and all the other things that are currently inaccessible on mobile. It could potentially just replace /components completely.
- [x] Identities and account security do not have the sidemenu visible in them. We could implement it in them, or include their main components (with the existing `<mat-sidenav>` wrappers removed) in the existing account-app architecture (components "injected" into account-app.component.html using subpaths. (https://github.com/runbox/runbox7/issues/817 and https://github.com/runbox/runbox7/issues/818)
- [x] Identities screen is not mobile friendly (widths hardcoded to too wide values) (https://github.com/runbox/runbox7/issues/819)
- [ ] Account security is not mobile friendly (some elements overlap or become too narrow in tables) (https://github.com/runbox/runbox7/issues/820)
- [x] The special offer on subscriptions page is not mobile friendly (button overlaps text) (https://github.com/runbox/runbox7/issues/821)
- [x] Addons cards are too wide and don't scale down on mobile screens (https://github.com/runbox/runbox7/issues/826)
- [x] Active Products table becomes too narrow to be readable on mobile *and* doesn't fit on the screen
- [x] Transactions table becomes too narrow to be readable on mobile *and* doesn't fit on the screen (https://github.com/runbox/runbox7/issues/827)
- [x] The shopping cart icon overlaps some page headers (including the shopping cart page itself). Maybe it should be moved to the toolbar, regardless of whether we're on mobile or not? (https://github.com/runbox/runbox7/issues/828)
- [x] The shopping cart table is too narrow to be readable (https://github.com/runbox/runbox7/issues/829)
- [x] The payment method cards are too big, overlap and don't fit on the screen (https://github.com/runbox/runbox7/issues/830)
- [x] The payment form(s) don't fit on mobile screens (https://github.com/runbox/runbox7/issues/831)

### CODE REVIEW

**Review by gtandersen — APPROVED** [review]
Looks great @tadzik, and I agree with your notes.

See also #424 regarding restructuring Account Products.

**Comment by tadzik** [comment]
3679dc8 implements a mobile-friendly renewals page, making the table narrower but with expandable rows:

active

The desktop version remains as it was.

**Comment by gtandersen** [comment]
Looks beautiful, @tadzik!

**Comment by tadzik** [comment]
The entire payment flow is now "mobilized" (with some nice-to-have tuneups pending in https://github.com/runbox/runbox7/issues/831). @kvviecien do I remember correctly that you were working on the identities, or was it something else that's in progress?

**Comment by kvviecien** [comment]
> The entire payment flow is now "mobilized" (with some nice-to-have tuneups pending in #831). @kvviecien do I remember correctly that you were working on the identities, or was it something else that's in progress?

That's right, I'm on identities, so you can grab another one :)

**Pull request merged**
