### PR TITLE
build(angular): Configuration update

### PR DESCRIPTION
**Pull request by kvviecien**
Helps with warnings about files needed for the rmm6 build.

### CODE REVIEW

**Comment by tadzik** [comment]
This isn't covered by our test suite, but it seems to break the rmm6 part of the build:

```
$ npm run buildrmm6
ERROR in ./src/main-rmm6.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /home/tadzik/src/runbox/runbox7/src/main-rmm6.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/home/tadzik/src/runbox/runbox7/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:933:23)
    at /home/tadzik/src/runbox/runbox7/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

Seems like the rmm6 build config in angular.json could use having its own `tsconfig.app.json` with the files that it needs – it's currently using the same one as the runbox7 bit, and so removing the runbox6 files from that one breaks the runbox6 build. Wanna try fixing that?

**Review by tadzik — CHANGES_REQUESTED** [review]
Needs fixes for `buildrmm6`

**Comment by castaway** [comment]
What's this one waiting on?

**Comment by kvviecien** [comment]
@castaway this PR actually didn't fix the problem, I say we close it and I'll open another one once this it figured out:

> This isn't covered by our test suite, but it seems to break the rmm6 part of the build:
> 
> ```
> $ npm run buildrmm6
> ERROR in ./src/main-rmm6.ts
> Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
> Error: /home/tadzik/src/runbox/runbox7/src/main-rmm6.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
>     at AngularCompilerPlugin.getCompiledFile (/home/tadzik/src/runbox/runbox7/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:933:23)
>     at /home/tadzik/src/runbox/runbox7/node_modules/@ngtools/webpack/src/loader.js:41:31
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ```
> 
> Seems like the rmm6 build config in angular.json could use having its own `tsconfig.app.json` with the files that it needs – it's currently using the same one as the runbox7 bit, and so removing the runbox6 files from that one breaks the runbox6 build. Wanna try fixing that?

**Pull request closed without merging**
