### PR TITLE
docs: lint and test instructions

### PR DESCRIPTION
**Pull request by petersalomonsen**
add instructions for lint and tests
update TOC

@tadzik We probably need instructions for running the license check scripts too?

### CODE REVIEW

**Comment by tadzik** [comment]
Perhaps it's best if we just integrate the license tests with the rest of the tests. I also noticed that right now they contain a non-core Perl dependency (`Path::Tiny`) so it'd even need separate things installed to be runnable.

Maybe it's better if we rewrite it in JS and make it run with the rest of the test suite.

**Comment by petersalomonsen** [comment]
yes maybe better to have it in JS if that's an easy fix @tadzik. Also considering recommending to set up travis-ci for the fork/branch before it's submitted as a PR. This can compensate for not running tests locally. What do you think? Have you set up a separate Travis CI for your fork? (shouldn't be more than registering your github account with https://travis-ci.com as far as I remember)

**Comment by tadzik** [comment]
Notes from yesterday's meeting:

– let's rewrite license tests in JS so that Perl is no longer a dependency and the tests themselves run along with `npm run test`, so that they don't need further explaining

– let's not compensate for running tests locally but rather make it easier to run tests locally – so that something like `npm run verify` runs `test`, `list`, `e2e` and `build` just like travis

These two should probably be done separately to not delay these fixes here.

**Comment by tadzik** [comment]
We can revisit this now that `npm run policy` is a thing.

**Comment by tadzik** [comment]
Forcepushed to reword your commit, now that policy tests require it :)

**Comment by tadzik** [comment]
I integrated the TOC changes in #373, now that the (updated) test instructions have been added.

**Pull request closed without merging**
