### PR TITLE
Piratefinn/gh 1033/mailheader improvements

### PR DESCRIPTION
**Pull request by piratefinn**
Addresses #1033 
Contact icon scaled down to 0.7 with transform on contactcard, icon resized to fit more with height of text and not overwhelm it and icon changed where relevant.

### CODE REVIEW

**Review by gtandersen — APPROVED** [review]
Looks good @piratefinn!

**Comment by gtandersen** [comment]
It would be even better if the subject line had the same left margin/padding as the other headers. :)
Runbox 7 message headers

**Comment by gtandersen** [comment]
And the expanded headers could benefit from the same indent:
Runbox 7 message headers expanded

**Comment by piratefinn** [comment]
> It would be even better if the subject line had the same left margin/padding as the other headers. :) Runbox 7 message headers

This one I was unsure on when I was initially adding the padding because I liked how it looked padded in line with the content, but if you wish it changed then I'll do that. The latter I'll do now.

**Comment by gtandersen** [comment]
Ideally all the headers and the content would have the same padding, perhaps?

**Pull request merged**
