### PR TITLE
fix(login): Complete rest of status error messages.

### PR DESCRIPTION
**Pull request by gtandersen**
The status error messages are now as follows:

**Status 1**
Status 1
**Status 2**
Status 2
**Status 3**
Status 3
**Status 4**
Status 4
**Status 5**
Status 5
**Status 6 and up**
Status 6

### CODE REVIEW

**Comment by gtandersen** [comment]
Does this look OK @runboxdave?

**Comment by runboxdave** [comment]
I was going to say that canceled has two lls unless you are in the US (which we are not) but actually it's not really a useful word because it kind of implies something different to it being closed when in fact it is just closed really. So maybe just used closed for Status 5 and up?

**Review by hernan604 — APPROVED** [review]

**Comment by hernan604** [comment]
@gtandersen its failing the lint tests. try to run: 

npm run lint        #should display where are the errors

npm run lint -- --fix     #it will try to autofix

**Comment by gtandersen** [comment]
@runboxdave The distinction was made because status 5 results from the customer initiating the closure (as in cancellation of the subscription), while status > 5 implies closure by staff regardless of any subscription.

**Comment by gtandersen** [comment]
@hernan604 Thanks; done now.

**Comment by runboxdave** [comment]
> @runboxdave The distinction was made because status 5 results from the customer initiating the closure (as in cancellation of the subscription), while status > 5 implies closure by staff regardless of any subscription.

Yes, I realise why the distinction is made. However, "cancelled" doesn't actually indicate what is intended (it could be cancelled by us and sounds somewhat brutal). Perhaps the response can be "Closed by customer" instead (or "cancelled by customer" if you prefer that)?

**Comment by gtandersen** [comment]
@runboxdave Yes, I see the point; however space is limited and for consistency I have changed the error message to "Your Runbox subscription has been canceled." for status 5 now.

For status > 5 the error is "This Runbox account has been closed.", such that a distinction is made between "subscription" and "account" in addition to "canceled" and "closed".

Hopefully this clarifies it sufficiently; otherwise we can make further improvements later.

**Comment by runboxdave** [comment]
Note that the status of the account (at least for Status 3 and 4) is disclosed to anyone trying to log in with a correct username but incorrect password. Given that usernames are generally public (i.e. they are email addresses) we are giving away account status when we shouldn't be.

**Comment by gtandersen** [comment]
@runboxdave Please open a new issue for this. :)

**Comment by gtandersen** [comment]
Already done in internal issue #1149.

**Pull request merged**
